#!/bin/bash
# run this script with one argument
# the goal is to find out if the argument is a file or a directory

if  [ -f $1 ]; then
	echo "$1 is a file"
elif [ -d $1 ]; then
	echo $1 "is a directory"
else
	echo "I do not know what $1 is"
fi
exit 0
