#!/bin/bash
#exemplo de entrada pelo utilizador
# Type ./testa_entrada_01 to execute this script

if [ -z $1 ]; then

	echo enter a name
	read NAME

else

	NAME=$1

fi
echo you have entered the text $NAME

exit 0

